### ISSUE TITLE
Issue with installing editable version of pymecht

### ISSUE THREAD

**Issue by r-williams-2** [ankushaggarwal/pymecht#23]
@rosnelclaire and I noticed an issue when installing the editable version of pyMechtT on Friday. The behaviour was that you could install pyMechT using `pip install -e .` in the cloned repo and it would appear installed when using `pip list`. Furthermore, the tests pass and when you run the examples.py file, it works. However, if you run the examples outside the pymecht folder, you get:
```
Traceback (most recent call last):
  File "/Users/ross/Documents/Uni/Postdoc_Aggarwal/pymecht/examples.py", line 160, in <module>
    mat_creation()
  File "/Users/ross/Documents/Uni/Postdoc_Aggarwal/pymecht/examples.py", line 8, in mat_creation
    material = MatModel('goh','nh')
               ^^^^^^^^
NameError: name 'MatModel' is not defined
```

**Comment by r-williams-2** [comment]
@rosnelclaire, is this still an issue? I realised that this is why we changed the method for developer installation but I had forgotten that it was ever a problem in the first place. Can you use `pip install -e .` now?

**Comment by r-williams-2** [comment]
@rosnelclaire has now tested this and it works as intended. As such, this will be marked as resolved.
